name: ai-ml-mastery-hub
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - jupyter>=1.0.0
  - jupyterlab>=3.0.0
  - ipywidgets>=7.6.0
  - plotly>=5.0.0
  - bokeh>=2.4.0
  - nltk>=3.7
  - opencv>=4.5.0
  - pillow>=8.3.0
  - tqdm>=4.62.0
  - requests>=2.26.0
  - pip
  - pip:
    - tensorflow>=2.8.0
    - torch>=1.11.0
    - torchvision>=0.12.0
    - transformers>=4.15.0
    - spacy>=3.4.0
    - auto-sklearn>=0.14.0
    - lime>=0.2.0
    - shap>=0.40.0
    - mlflow>=1.20.0
    - wandb>=0.12.0
    - fastapi>=0.70.0
    - streamlit>=1.5.0
    - python-dotenv>=0.19.0
    - black>=21.9.0
    - flake8>=4.0.0
    - pytest>=6.2.0